---

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_REF_PROTECTED == "true"

stages:
  - check
  - build
  - release
  - manifest

variables:
  DOCKER_OPTS: ${DOCKER_OPTS} --registry-mirror=https://mirror.gcr.io
  FF_SCRIPT_SECTIONS: true

.template:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  tags:
    - schedmd-runners

include:
  - local: .gitlab/ci/check.yml
  - local: .gitlab/ci/slurm.yml
