---

stages:
  - build
  - release

default:
  image: docker:27.3.0
  services:
    - docker:27.3.0-rc.1-dind
  before_script:
    - docker info
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: /certs

.slurm:
  variables:
    DOCKER_BAKE_REGISTRY: $CI_REGISTRY_IMAGE
  parallel:
    matrix:
      - VERSION:
          - master
          - '24.05'
        FLAVOR:
          - rockylinux-9
          - ubuntu-24.04

.slurm-release:
  variables:
    DOCKER_SOURCE_REGISTRY: $CI_REGISTRY_IMAGE
    DOCKER_TARGET_REGISTRY: $DOCKER_REGISTRY
  parallel:
    matrix:
      - VERSION:
          - '24.05'
        FLAVOR:
          - rockylinux-9
          - ubuntu-24.04

build:
  stage: build
  extends: .slurm
  script:
    - export BAKE_TARGET="$(printf "%s_%s" "$(echo "$VERSION" | sed 's/[[:punct:]]//g')" "$(echo "$FLAVOR" | sed 's/[[:punct:]]//g')")"
    - echo "BAKE_TARGET=$BAKE_TARGET"
    - cd ./schedmd/slurm/
    - docker buildx bake --print $BAKE_TARGET
    - docker buildx bake --progress=plain $BAKE_TARGET
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release-.*/
      changes:
        - schedmd/slurm/$FLAVOR/*

push:
  stage: build
  extends: .slurm
  script:
    - export BAKE_TARGET="$(printf "%s_%s" "$(echo "$VERSION" | sed 's/[[:punct:]]//g')" "$(echo "$FLAVOR" | sed 's/[[:punct:]]//g')")"
    - echo "BAKE_TARGET=$BAKE_TARGET"
    - cd ./schedmd/slurm/
    - docker buildx bake --print $BAKE_TARGET
    - docker buildx bake --progress=plain --push $BAKE_TARGET
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release-.*/
      changes:
        - schedmd/slurm/$FLAVOR/*

release:
  stage: release
  extends: .slurm-release
  script:
    - |
      if [ -z $DOCKER_REGISTRY_PASSWORD ] || [ -z $DOCKER_REGISTRY ] || [ -z $DOCKER_REGISTRY_USER ]; then
        echo "Runner lacks login info. Either environment variables are not defined, or runner is on an unprotected branch/tag.";
        exit 1;
      fi
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login $DOCKER_REGISTRY -u $DOCKER_REGISTRY_USER --password-stdin
    - apk update && apk upgrade
    - apk add --no-cache bash jq
    - |
      for daemon in slurmctld slurmd slurmdbd slurmrestd sackd ; do
        ./scripts/build.sh --registry=$DOCKER_SOURCE_REGISTRY --new-registry=$DOCKER_TARGET_REGISTRY --target=$daemon --slurm-version=$VERSION --pull --no-build --push ./schedmd/slurm/$FLAVOR ;
      done
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH =~ /^release-.*/
      when: manual
